/**
 * UI 元件 barrel（FOLDER #15）：常用 named export 集中，可選 from '@/components/ui'
 * 含 default 的組件（如 FeatureIcon、ScrollProgress）仍建議直接 from '@/components/ui/XXX'
 */
export { BackToTop } from './BackToTop'
export { Badge } from './Badge'
export { Carousel } from './Carousel'
export { Breadcrumb } from './Breadcrumb'
export { ConfirmDialog } from './ConfirmDialog'
export { CountUp } from './CountUp'
export { EmptyState } from './EmptyState'
export { InViewAnimate } from './InViewAnimate'
export { MagneticButton } from './MagneticButton'
export { ModalCloseButton } from './ModalCloseButton'
export { PageTransition } from './PageTransition'
export { Pagination } from './Pagination'
export { Select } from './Select'
export type { SelectProps, SelectOption } from './Select'
export { Skeleton, SkeletonCard, SkeletonText } from './Skeleton'
export { Divider } from './Divider'
export { FormFieldError } from './FormFieldError'
export { Loader } from './Loader'
export { Switch } from './Switch'
export { ProgressBar } from './ProgressBar'
export { Tooltip } from './Tooltip'
export { ImageWithFallback } from './ImageWithFallback'
export { Accordion, AccordionItem } from './Accordion'
export { RouteChangeProgress } from './RouteChangeProgress'
export { Icon } from './Icon'
export type { IconName } from './Icon'
export { Avatar } from './Avatar'
export { CopyButton } from './CopyButton'
export { Slider } from './Slider'
export { Table } from './Table'
export { PasswordStrength } from './PasswordStrength'
export { Modal } from './Modal'
